myproject/myproject/urls.py
from django.contrib import admin
from . import views
from django.urls import include, path


urlpatterns = [

    path('admin/', admin.site.urls),
    path("poll/", include("poll.urls")),
    path('',views.index,name='index'),
    
    path('geeks/', views.geeks, name='geeks'),
    path("__debug__/",include("dabug_toolbar.urls")),


    path('harry_notes/', views.harry_notes, name='harry_notes'),
    
    path('youtube_lecture/', views.youtube_lecture, name='youtube_lecture'),
    
    path('django_docs/',views.django_docs, name='django_docs'),
    path('working/', views.working,name="work")
]

myproject/poll/urls.py
from django.urls import path

from . import views


app_name="poll"
urlpatterns = [
    path("__debug__/",include("dabug_toolbar.urls")),
    path("", views.indexView.as_view(), name="index"),
    path("<int:pk>/",views.DetailView.as_view(),name="detail"),
    path("<int:pk>/results",views.ResultsView.as_view(),name="results"),
    path("<int:question_id>/vote",views.vote,name="vote"),
]

myproject/poll/models.py
# Create your models here.
from django.db import models
import datetime
from django.contrib import admin
from django.utils import timezone


class Question(models.Model):
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
   


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

myproject/myproject/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse('''<!DOCTYPE html>
<html>
<head>
    <title>Index Page</title>
</head>
<body>
    <h1>Index Page</h1>
    <ul>
        <li><a href="http://127.0.0.1:8000/geeks/">GeeksforGeeks</a></li>
        <li><a href="http://127.0.0.1:8000/harry_notes/">Code with Harry Notes</a></li>
        <li><a href="http://127.0.0.1:8000/youtube_lecture/">YouTube Lecture</a></li>
        <li><a href="http://127.0.0.1:8000/django_docs/">Django Documentation</a></li>
    </ul>
</body>
</html>
''')

def geeks(request):
    text=request.GET.get('text')
    print("text",text)
    return HttpResponse('''<h1>Welcome</h1> link : <a href="https://www.geeksforgeeks.org/django-introduction-and-installation/"> click here for geeks for geeks notes</a> {{ text }}''')

def harry_notes(request):
    return HttpResponse('''<h1>Home</h1> link : <a href="https://www.codewithharry.com/videos/python-django-tutorials-hindi-5/" >click to reach code with harry notes</a>''')

def youtube_lecture(request):
    return HttpResponse('''<h1>YouTube Lecture link:</h1> <a href="https://www.youtube.com/watch?v=AepgWsROO4k&list=PLu0W_9lII9ah7DDtYtflgwMwpT3xmjXY9&index=7" > click here to watch the video now </a>''')

def django_docs(request):
    return HttpResponse('''<h1>Django Documentation link:</h1> <a href="https://docs.djangoproject.com/en/4.2/intro/tutorial01/">click here to access the documentation</a>''')

def working(request):
    return render(request,"index.html")

myproject/poll/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.http import Http404
from django.views import generic
from django.utils import timezone

from .models import Question,Choice

# Create your views here.

class indexView(generic.ListView):
    template_name="poll/index.html"
    context_object_name="latest_question_list"
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]
    

class DetailView(generic.DetailView):
    model=Question
    template_name="poll/detail.html"
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model =Question
    template_name="poll/results.html"


def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST["choice"])
    except(KeyError,Choice.DoesnotExist):
        return redner(
            request,
            "poll/detail.html",
            {
                "question": question,
                "error_message": "you didn't select a choice",
            },
        )
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse("poll:results",args=(question.id,)))
        

myproject/poll/templates/poll/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>hello guys details dekhlo</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>{{ question.question_text }}</h1>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}</li>
        {% endfor %}
        </ul>

        <form action="{% url 'poll:vote' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
            </form>

        <script src="" async defer></script>
    </body>
</html>

myproject/poll/templates/poll/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>poll quize</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" href="{% static 'poll/style.css' %}">
    </head>
    <body>
        {% if latest_question_list %}
            <ul>
                {% for question in latest_question_list %}
                    {% comment %} <li><a href="/poll/{{ question.id }}/">{{ question.question_text }}</a></li> {% endcomment %}
                    <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No poll are available.</p>
        {% endif %}
        
        <script src="" async defer></script>
    </body>
</html>

myproject/poll/templates/poll/results.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>{{ question.question_text }}</h1>

        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        </ul>

        <a href="{% url 'poll:detail' question.id %}">Vote again?</a>
        
        <script src="" async defer></script>
    </body>
</html>

myproject/templates/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>first template of the course</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        look at me guys i'm working
        <form action="/geeks/" method='get'>
            <textarea name="text" style="width: 1314px; height: 86px;"> </textarea>
            <button type="submit">analyze</button>
        <script src="" async defer></script>
    </body>
</html>